### ISSUE TITLE
Deprecated: setOnTabSelectedListener()

### ISSUE THREAD

**Issue by ArchitKhanna** [David-Bromell/Android-Development-Project#27]
- setOnTabSelectedListener() has been deprecated and an alternate may be available; 
- Try a work around or fix that won't lead to an issue with the app in the future;

**Comment by ArchitKhanna** [comment]
![deprecated](https://user-images.githubusercontent.com/18014745/80369998-199e7900-8887-11ea-9a27-e1a5c3142b40.JPG)

**Comment by ArchitKhanna** [comment]
- Can be found in the 'MessageTabsActivity.java' file;

**Comment by David-Bromell** [comment]
AK, I will look into this and see if there is an alternative method
